export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_PROGRESS = "SET_PROGRESS";
export const APP_LOAD = 'APP_LOAD'
// export const SETTINGS_SAVED = 'SETTINGS_SAVED'
export const ADD_MEME = 'ADD_MEME'
export const DELETE_MEME = 'DELETE_MEME'
export const GET_MEMES = 'GET_MEMES'
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const JOIN_GROUP = 'JOIN_GROUP'
export const LEAVE_GROUP = 'LEAVE_GROUP'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
// export const ASYNC_START = 'ASYNC_START'
// export const ASYNC_END = 'ASYNC_END'
// export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED'
// export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED'
